### ISSUE TITLE
npm start报错

### ISSUE THREAD

**Issue by cd756819220** [skyvow/m-mall-admin#65]
eastMBP:m-mall-admin-master east$ npm start

> m-mall-admin@1.0.0 start /Users/east/wx_develop/mall/m-mall-admin-master
> babel-node ./bin/www

/Users/east/wx_develop/mall/m-mall-admin-master/node_modules/log4js/lib/configuration.js:25
      throw new Error(`Problem with log4js configuration: (${util.inspect(config, { depth: 5 })})`
      ^

Error: Problem with log4js configuration: ({ appenders:
   [ { type: 'console' },
     { type: 'file',
       filename: 'logs/access.log',
       maxLogSize: 1024,
       backups: 4,
       category: 'normal' } ],
  replaceConsole: true }) - must have a property "appenders" of type object.
    at tests.forEach (/Users/east/wx_develop/mall/m-mall-admin-master/node_modules/log4js/lib/configuration.js:25:13)
    at Array.forEach (<anonymous>)
    at Object.throwExceptionIf (/Users/east/wx_develop/mall/m-mall-admin-master/node_modules/log4js/lib/configuration.js:23:9)
    at configuration.addListener (/Users/east/wx_develop/mall/m-mall-admin-master/node_modules/log4js/lib/appenders/index.js:80:17)
    at listeners.forEach.listener (/Users/east/wx_develop/mall/m-mall-admin-master/node_modules/log4js/lib/configuration.js:36:33)
    at Array.forEach (<anonymous>)
    at Object.configure (/Users/east/wx_develop/mall/m-mall-admin-master/node_modules/log4js/lib/configuration.js:36:13)
    at Object.configure (/Users/east/wx_develop/mall/m-mall-admin-master/node_modules/log4js/lib/log4js.js:62:17)
    at Object.<anonymous> (/Users/east/wx_develop/mall/m-mall-admin-master/common/logger.js:3:8)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at loader (/Users/east/wx_develop/mall/m-mall-admin-master/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/east/wx_develop/mall/m-mall-admin-master/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/east/wx_develop/mall/m-mall-admin-master/app.js:17:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at loader (/Users/east/wx_develop/mall/m-mall-admin-master/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/east/wx_develop/mall/m-mall-admin-master/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! m-mall-admin@1.0.0 start: `babel-node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the m-mall-admin@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/east/.npm/_logs/2019-05-06T13_13_32_114Z-debug.log

是因为我的版本不对么？node v10.12.0   npm npm@6.4.1   db version v4.0.9  Redis version=5.0.4, bits=64

**Comment by cd756819220** [comment]
重新来一遍又好了。还是之前的软件版本。之前是把package.json里面包都改成最新的，可能用法不兼容了。
