### ISSUE TITLE
启动项目mongodb启动报错

### ISSUE THREAD

**Issue by bill315** [skyvow/m-mall-admin#66]
请问npm 启动这个错误咋解决？（mongodb redis 都启动）
E:\study\mall\m-mall-admin-master\node_modules\_session-mongoose@0.5.2@session-mongoose\index.js:97
          this.model = connection.model(this.options.modelName, SessionSchema);
                                  ^

TypeError: connection.model is not a function
    at new SessionStore (E:\study\mall\m-mall-admin-master\node_modules\_session-mongoose@0.5.2@session-mongoose\index.js:97:35)
    at Object.<anonymous> (E:/study/mall/m-mall-admin-master/app.js:26:15)

**Comment by WHHCNN** [comment]
一样报错，兄弟，找到解决方法了么

**Comment by skyvow** [comment]
试试重新 `npm install` 不要用淘宝镜像(cnpm)。
